services:
  postgres:
    image: postgres:16
    container_name: E-Commerce
    restart: always
    environment:
      POSTGRES_USER: ECommerce
      POSTGRES_PASSWORD: ECommerce
      POSTGRES_DB: ECommerce
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
